<center> </center>

<center><font size=5 face="Helvetica" color=#EE4B2B><b>
Pytorch Tutorial: Tensors
</b></font></center>

<center><font face="Helvetica" size=3><b>Ang Chen</b></font></center>
<center><font face="Helvetica" size=3>July, 2024</font></center>

***

Tensors are a specialized data structure that are very similar to arrays and matrices.
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model's parameters.

Tensors are similar to NumPy's ndarrays, except that tensors can run on GPUs or other hardware accelerators.
In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data.
Tensor are also optimized for automatic differentiation. 
If you're familiar with ndarrays, you'll be right at home with the Tensor API.
If not, follow along!

In [1]:
import torch
import numpy as np

# Initializing a Tensor

Tensors can be initialized in a various ways.
Take a look at the following examples:

**Directly from data**

Tensors can be created from data directly.
The data type is automatically inferred.

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**From a NumPy array**
Tensors can be created from NumPy arrays.

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

**From another tensor**:
The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [4]:
x_ones = torch.ones_like(x_data)
x_ones, type(x_ones)

(tensor([[1, 1],
         [1, 1]]),
 torch.Tensor)

**With random or constant values**:

$\texttt{shape}$ is a tuple of tensor dimensions.
In the functions below, it determines the dimensionality of the output tensor.

In [5]:
shape = (2,3,)
shape

(2, 3)

In [6]:
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.8183, 0.4146, 0.6323],
         [0.6133, 0.5615, 0.3799]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

# Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [7]:
tensor = torch.rand(3,4)

In [8]:
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

# Operations on Tensors

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling.

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU) or MPS.
If you're using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU

In [13]:
if torch.backends.mps.is_available():
    tensor = tensor.to("mps")

In [11]:
tensor

tensor([[0.5129, 0.7192, 0.5486, 0.9046],
        [0.1891, 0.1275, 0.3551, 0.3424],
        [0.8234, 0.4741, 0.3702, 0.2904]], device='mps:0')

Try out some of the operations from the list.
If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.